CREATE TABLE IF NOT EXISTS USER_ALL
(
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    USER_NAME varchar(60) NOT NULL,
    PASSWORD varchar(60) NOT NULL,
    EMAIL varchar(60) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY ID_USER_ALL_UNIQUE (`ID`)
);

CREATE TABLE IF NOT EXISTS MARK
(
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NAME varchar(60) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY ID_MARK_UNIQUE (`ID`)
);

CREATE TABLE IF NOT EXISTS PATRIMONY
(
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NAME varchar(60) NOT NULL,
    DESCRIPTION varchar(60) NULL,
    NUM_TUMBLE bigint(20) NOT NULL,
    ID_MARK bigint(20) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY ID_PATRIMONY_UNIQUE (`ID`)
);


insert into USER_ALL(ID, USER_NAME, EMAIL, PASSWORD) VALUES (1010, 'user', 'user@user.com', 'user');

insert into MARK(ID, NAME) VALUES (2001, 'MARCA 1');
insert into MARK(ID, NAME) VALUES (2002, 'MARCA 2');

insert into PATRIMONY(ID, NAME, DESCRIPTION, NUM_TUMBLE, ID_MARK) VALUES (1001, 'CASA 100', 'CASA PERTO DO MERCADO', 2001, 2001);
insert into PATRIMONY(ID, NAME, DESCRIPTION, NUM_TUMBLE, ID_MARK) VALUES (1002, 'CASA 101', 'CASA PERTO DO CAMPO DE FUTEBOL', 1002, 2002);