insert into USER_ALL(ID, USER_NAME, EMAIL, PASSWORD) VALUES (1010, 'user', 'user@user.com', 'user');

insert into MARK(ID, NAME) VALUES (2001, 'MARCA 1');
insert into MARK(ID, NAME) VALUES (2002, 'MARCA 2');
insert into MARK(ID, NAME) VALUES (2003, 'MARCA 3');

insert into PATRIMONY(ID, NAME, DESCRIPTION, NUM_TUMBLE, ID_MARK) VALUES (1001, 'CASA 100', 'CASA PERTO DO MERCADO', 2001, 2001);
insert into PATRIMONY(ID, NAME, DESCRIPTION, NUM_TUMBLE, ID_MARK) VALUES (1002, 'CASA 101', 'CASA PERTO DO CAMPO DE FUTEBOL', 1002, 2002);