CREATE TABLE IF NOT EXISTS USER_ALL
(
    ID NUMBER(10,0) NOT NULL,
    USER_NAME VARCHAR2(60) NOT NULL,
    PASSWORD VARCHAR2(60) NOT NULL,
    EMAIL VARCHAR2(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS MARK
(
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS PATRIMONY
(
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(60) NOT NULL,
    DESCRIPTION VARCHAR2(60) NULL,
    NUM_TUMBLE NUMBER(10,1) NOT NULL,
    ID_MARK NUMBER(10,1) NOT NULL
);